name: CI

on:
  pull_request:
    branches:
      - develop
      - main
      - v1
  push:
    branches:
      - develop
      - main
      - v1

env:
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm test
